version: '3.5'
services:

  latency:
    build: .
    container_name: maplestory-latency
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - '3005:3005'
